name: C/C++ CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ~/
        
    steps:
    - uses: actions/checkout@v4
    - name: 쉘 스크립트 실행
      run: |
        pwd
        sudo ./deploy.sh
